config/routes.rb
Rails.application.routes.draw do
  root to: 'restaurants#index'

  # Generates the 7 CRUD actions
  # resources :restaurant
  # resources :restaurant, except: %i[destroy update edit create new]
  resources :restaurant, only: %i[index show]

  # Create - 2 routes
  # Shows the create form
  # get '/restaurants/new', to: 'restaurants#new'
  # post '/restaurants', to: 'restaurants#create'

  # get '/restaurants', to: 'restaurants#index'
  # get '/restaurants/:id', to: 'restaurants#show', as: :restaurant

  # Update - 2 routes
  # get '/restaurants/:id/edit', to: 'restaurants#edit'
  # patch '/restaurants/:id', to: 'restaurants#update'

  # DESTROY the restaurant
  # delete '/restaurants/:id', to: 'restaurants#destroy', as: :delete_restaurant
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  def good?
    rating > 3
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  # after_action
  # around_action

  # before filter
  before_action :set_restaurant, only: %i[show edit update destroy]

  def index
    @restaurants = Restaurant.all
  end

  # GET /restaraunts/:id
  def show
  end

  # GET /restaurants/new
  def new
    @restaurant = Restaurant.new
  end

  # POST /restaurants
  def create
    @restaurant = Restaurant.new(restaurant_params)
    @restaurant.save

    redirect_to root_path
  end

  # GET /restaurants/:id/edit
  def edit
  end

  # PATCH /restaurants/:id
  def update
    @restaurant.update(restaurant_params)

    redirect_to root_path
  end

  # DELETE /restaurants/:id
  def destroy
    @restaurant.destroy

    redirect_to root_path
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :rating, :address)
  end

  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsCrud</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/_form.html.erb
<%= form_with model: restaurant do |f| %>
  <div>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div>
    <%= f.label :rating %>
    <%= f.number_field :rating %>
  </div>

  <div>
    <%= f.label :address %>
    <%= f.text_field :address %>
  </div>

  <%= f.submit %>
<% end %>

app/views/restaurants/edit.html.erb
<h2>Edit restaurant</h2>

<%= render 'form', restaurant: @restaurant %>

app/views/restaurants/index.html.erb
<h2>List of restaurants</h2>

<ul>
  <% @restaurants.each do |restaurant| %>
    <li>
      <%= link_to restaurant.name, restaurant_path(restaurant) %> (<%= restaurant.id %>)
      <%= link_to 'DESTROY!', delete_restaurant_path(restaurant), data: {
        turbo_method: 'delete',
        turbo_confirm: 'Are you sure?'
      } %>
    </li>
  <% end %>
</ul>

app/views/restaurants/new.html.erb
<h2>Create new restaurant</h2>

<%= render 'form', restaurant: @restaurant %>
<%#= render partial: 'form', locals: { restaurant: @restaurant } %>

app/views/restaurants/show.html.erb
<h2>Restaurant details</h2>

<p><%= link_to '<< Back', root_path %></p>

<ul>
  <li>Name: <%= @restaurant.name %></li>
  <li>Address: <%= @restaurant.address %></li>
  <li>Rating: <%= @restaurant.rating %></li>
</ul>